version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    versioning-strategy: widen
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: npm
    directory: /src/ephemeral-map
    versioning-strategy: widen
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: npm
    directory: /src/mutex
    versioning-strategy: widen
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: npm
    directory: /src/result
    versioning-strategy: widen
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: npm
    directory: /src/timestore
    versioning-strategy: widen
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
