name: EphemeralMap CI

on:
  push:
    branches: [main]
    paths:
      - src/ephemeral-map/**
  pull_request:
    paths:
      - src/ephemeral-map/**

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
      fail-fast: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build timestore
        run: npm run build --workspace=src/timestore
      - name: Run tests
        run: npm run test --workspace=src/ephemeral-map
